CREATE DATABASE DESAFIO_ROIT
GO

USE DESAFIO_ROIT
GO

UPDATE CNAE 
SET cod_cnae_fiscal_secundaria = NULLIF(cod_cnae_fiscal_secundaria, 0)

'PRIMEIRA VIEW 3.1'
CREATE VIEW CNPJ_SEM_CNAE_SECUNDARIO AS
SELECT CNAE.cnpj_basico
FROM CNAE
GROUP BY CNAE.cnpj_basico
HAVING SUM(CASE WHEN CNAE.cod_cnae_fiscal_secundaria IS NULL THEN 0 ELSE 1 END) = 0
GO

CREATE VIEW CNPJ_SEM_CNAE_SECUNDARIO_PR AS
SELECT CNPJ_SEM_CNAE_SECUNDARIO.cnpj_basico, ESTABELECIMENTOS.end_uf FROM CNPJ_SEM_CNAE_SECUNDARIO
JOIN ESTABELECIMENTOS  ON (ESTABELECIMENTOS.cnpj_basico = CNPJ_SEM_CNAE_SECUNDARIO.cnpj_basico) 
WHERE end_uf = 'PR'
GO

CREATE VIEW quantidade_cnpj_sem_cnae_secundario as
SELECT COUNT(cnpj_basico) AS QUANTIDADE 
FROM CNPJ_SEM_CNAE_SECUNDARIO_PR
GO

'SEGUNDA VIEW 3.2'
CREATE VIEW QTDE_ESTAB_C_CNAE_4530703 AS
SELECT COUNT(*) AS quantidade
FROM CNAE
WHERE cod_cnae_fiscal_secundaria = '4530703'
GO

'TERCEIRA VIEW 3.3'
CREATE VIEW QTDE_ESTAB_C_CNAE_4530703_EM_EMPRESAS AS
SELECT COUNT(*) AS quantidade
FROM CNAE
JOIN EMPRESA ON (EMPRESA.cnpj_basico = CNAE.cnpj_basico)
WHERE cod_cnae_fiscal_secundaria = '4530703'
GO

'QUARTA VIEW 3.4'
CREATE VIEW ESTABELECIMENTOS_e_QUANTIDADE_CNAE AS
SELECT cnpj_basico, SUM(CASE WHEN CNAE.cod_cnae_fiscal_secundaria IS NULL THEN 0 ELSE 1 END) AS quantidade
FROM CNAE
GROUP BY CNAE.cnpj_basico
GO

CREATE VIEW TOP10_ESTABELECIMENTOS_COM_MAIS_CNAE_SECUNDARIO AS
SELECT TOP (10) ESTABELECIMENTOS_e_QUANTIDADE_CNAE.cnpj_basico, ESTABELECIMENTOS_e_QUANTIDADE_CNAE.quantidade, ESTABELECIMENTOS.end_uf
FROM ESTABELECIMENTOS_e_QUANTIDADE_CNAE
JOIN ESTABELECIMENTOS ON (ESTABELECIMENTOS_e_QUANTIDADE_CNAE.cnpj_basico = ESTABELECIMENTOS.cnpj_basico)
WHERE ESTABELECIMENTOS.end_uf = 'SC' OR ESTABELECIMENTOS.end_uf = 'SP'
ORDER BY ESTABELECIMENTOS_e_QUANTIDADE_CNAE.quantidade DESC
GO
